In [1]:
import time

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.utils.data as data

# %matplotlib inline
from IPython.display import set_matplotlib_formats
from matplotlib.colors import to_rgba
from tqdm.notebook import tqdm  # Progress bar

set_matplotlib_formats("svg", "pdf")

In [2]:
print("Using torch", torch.__version__)

Using torch 1.9.1+cpu


In [3]:
torch.manual_seed(42)

create tensor

In [4]:
x = torch.Tensor(2, 3, 4)
print(x)

tensor([[[1.0561e-38, 8.9082e-39, 9.9184e-39, 1.0286e-38],
         [9.0919e-39, 8.9082e-39, 9.2755e-39, 8.9082e-39],
         [8.9082e-39, 1.0194e-38, 9.1837e-39, 4.6837e-39]],

        [[9.9184e-39, 9.0000e-39, 1.0561e-38, 1.0653e-38],
         [4.1327e-39, 8.9082e-39, 9.8265e-39, 9.4592e-39],
         [1.0561e-38, 6.7041e-39, 1.1112e-38, 9.5511e-39]]])


In [5]:
# Create a tensor from a (nested) list
x = torch.Tensor([[1, 2], [3, 4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [6]:
# Create a tensor with random values between 0 and 1 with the shape [2, 3, 4]
x = torch.rand(2, 3, 4)
print(x)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])


In [7]:
shape = x.shape
print("Shape:", x.shape)

size = x.size()
print("Size:", size)

dim1, dim2, dim3 = x.size()
print("Size:", dim1, dim2, dim3)

Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Size: 2 3 4


In [8]:
np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [9]:
tensor = torch.arange(4)
np_arr = tensor.numpy()

print("PyTorch tensor:", tensor)
print("Numpy array:", np_arr)

PyTorch tensor: tensor([0, 1, 2, 3])
Numpy array: [0 1 2 3]


tensor to numpy only on the cpu, if tensor on the GPU,using tensor.cpu().numpy()