In [1]:
import time

import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.utils.data as data

# %matplotlib inline
from IPython.display import set_matplotlib_formats
from matplotlib.colors import to_rgba
from tqdm.notebook import tqdm  # Progress bar

set_matplotlib_formats("svg", "pdf")

In [2]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
y = x1 + x2

print("X1", x1)
print("X2", x2)
print("Y", y)

X1 tensor([[0.4979, 0.1175, 0.6642],
        [0.0310, 0.2642, 0.4800]])
X2 tensor([[0.4780, 0.5304, 0.9324],
        [0.3377, 0.1503, 0.3548]])
Y tensor([[0.9758, 0.6478, 1.5966],
        [0.3687, 0.4145, 0.8347]])


In [3]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
print("X1 (before)", x1)
print("X2 (before)", x2)

x2.add_(x1)
print("X1 (after)", x1)
print("X2 (after)", x2)

X1 (before) tensor([[0.2211, 0.1694, 0.3484],
        [0.6844, 0.9891, 0.1292]])
X2 (before) tensor([[0.3740, 0.7322, 0.8556],
        [0.2480, 0.7190, 0.1684]])
X1 (after) tensor([[0.2211, 0.1694, 0.3484],
        [0.6844, 0.9891, 0.1292]])
X2 (after) tensor([[0.5951, 0.9016, 1.2040],
        [0.9324, 1.7082, 0.2976]])


In [4]:
x = torch.arange(6)
print("X", x)

X tensor([0, 1, 2, 3, 4, 5])


In [5]:
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [6]:
x = x.permute(1, 0)  # Swapping dimension 0 and 1
print("X", x)

X tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [7]:
x = torch.arange(6)
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [8]:
W = torch.arange(9).view(3, 3)  # We can also stack multiple operations in a single line
print("W", W)

W tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [9]:
h = torch.matmul(x, W)  # Verify the result by calculating it by hand too!
print("h", h)

h tensor([[15, 18, 21],
        [42, 54, 66]])


# Indexing

In [10]:
x = torch.arange(12).view(3, 4)
print("X", x)

X tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [11]:
print(x[:, 1])  # Second column

tensor([1, 5, 9])


In [12]:
print(x[0])  # First row

tensor([0, 1, 2, 3])


In [13]:
print(x[:2, -1])  # First two rows, last column

tensor([3, 7])


In [14]:
print(x[1:3, :])  # Middle two rows

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
